spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
#    url: jdbc:postgresql://localhost:5432/yourpm_db
#    username: postgres
#    password: postgres
  jpa:
    show-sql: false
#  mail:
#    host: smtp.mail.ru
#    port: 465
#    username: your_pm_swd@mail.ru
#    password: 2Gbc6QpDxex8f5AHcJ88
#    test-connection: true
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
server:
  port: 8080
